name: C/C++ CI

on:
  push:
    branches: [ "main", "development", "experimental", "test*" ]
  pull_request:
    branches: [ "main", "development", "experimental", "test*" ]

jobs:
  build:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:        
        runs-on: [ubuntu-latest, ubuntu-22.04, macos-latest, macos-14 ]
        python-version: [ "3.10", "3.12" ]

    steps:
    - uses: actions/checkout@v4

    - name: C++ info
      run: g++ -v

    - name: Install dependencies (Ubuntu)
      run: sudo apt-get install -y nlohmann-json3-dev
      if: ${{ contains(matrix.runs-on, 'ubuntu') }}
      
    - name: Install dependencies (macOS)
      run: brew install nlohmann-json
      if: ${{ contains(matrix.runs-on, 'macos') }}

    - name: make
      run: make
      
    - name: list generated files
      run: |
          ls -alth
